
spring:
  mustache:
    suffix: .html
  datasource:
    url: jdbc:mariadb://3.35.91.181:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: burger
    password: burger123!
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
